---
booktitle: Proceedings of the First Teaching Machine Learning and Artificial Intelligence
  Workshop
shortname: TeachML
volume: 141
year: '2020'
start: 2020-09-14
end: 2020-09-14
published: 2021-03-29
url: https://proceedings.mlr.press
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: TeachML-2020
month: 0
cycles: false
bibtex_editor: Bischl, Bernd and Guhr, Oliver and Seibold, Heidi and Steinbach, Peter
editor:
- given: Bernd
  family: Bischl
- given: Oliver
  family: Guhr
- given: Heidi
  family: Seibold
- given: Peter
  family: Steinbach
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the First Teaching Machine Learning and Artificial Intelligence Workshop
    Held in Virtual Conference on 14 September 2020

  Published as Volume 141 by the Proceedings of Machine Learning Research on 29 March 2021.

  Volume Edited by:
    Bernd Bischl
    Oliver Guhr
    Heidi Seibold
    Peter Steinbach

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 14 Sep
author:
  name: PMLR
baseurl: "/v141"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v141
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: European Conference on Machine Learning and Principles and Practice of Knowledge
    Discovery in Databases
  url:
  location: Virtual Conference
  dates:
  - 2020-09-14
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v141/teachml20.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v141/teachml20.bib
